"""Where OpenJevX data lives: ~/openjevx/data (or $OPENJEVX_DATA). Code stays in the repo.

  raw/       downloaded source datasets           incoming/  converted source datasets
  train/     training sets (*_train.jsonl, train_openjevx.jsonl, jev_train_all.jsonl)
  eval/      test sets (eval_openjevx.jsonl, *_eval.jsonl, cases_*.jsonl, test.json, questions_1000.csv)
  gate/      release-gate sets (basics_gate.jsonl, conditions_basics_gate.jsonl)
  work/      generated by the pipeline: leak/, shards/, runs/, gate/, quality/, samples/
"""
import os
from pathlib import Path

DATA = Path(os.environ.get("OPENJEVX_DATA", Path.home() / "openjevx" / "data")).expanduser()
RAW, INCOMING = DATA / "raw", DATA / "incoming"
TRAIN, EVAL, GATE = DATA / "train", DATA / "eval", DATA / "gate"
WORK = DATA / "work"
