#!/bin/bash
# Write the two paste-able files, deploy/cloud-init.yaml and deploy/docker-compose.yml, from deploy/VERSION.
# They pin the commit that last changed what they fetch (immutable, unlike main) and install.sh's sha256.
# Commit your changes to install.sh / Dockerfile first, then:  deploy/render.sh   (or --check in CI)
set -euo pipefail
cd "$(dirname "$0")/.."
version="$(cat deploy/VERSION)"
repo=muthuishere/openjevx

install_ref="$(git log -1 --format=%H -- deploy/install.sh)"
git diff --quiet "$install_ref" -- deploy/install.sh || { echo "render.sh: commit deploy/install.sh first" >&2; exit 1; }
install_sum="$(git show "$install_ref:deploy/install.sh" | shasum -a 256 | cut -d' ' -f1)"
image_ref="$(git log -1 --format=%H -- Dockerfile deploy/docker-entrypoint.sh deploy/VERSION)"
git diff --quiet "$image_ref" -- Dockerfile deploy/docker-entrypoint.sh deploy/VERSION || { echo "render.sh: commit Dockerfile, deploy/docker-entrypoint.sh and deploy/VERSION first" >&2; exit 1; }

cloud_init="#cloud-config
# OpenJevX $version on any Ubuntu/Debian VPS (AWS, Azure, GCP, DigitalOcean, Hetzner, ...): paste this as the
# instance's user data. Needs linux amd64 and at least 2 GB RAM. Afterwards:
#   ssh in, cat /root/openjevx-password, curl http://127.0.0.1:21118/health
# Generated by deploy/render.sh from deploy/VERSION: install.sh is pinned to a commit and checked by sha256.
package_update: true
packages: [curl, ca-certificates, ufw]
runcmd:
  - curl -fsSL https://raw.githubusercontent.com/$repo/$install_ref/deploy/install.sh -o /root/openjevx-install.sh
  - echo '$install_sum  /root/openjevx-install.sh' | sha256sum -c - && OPENJEVX_VERSION=$version bash /root/openjevx-install.sh"

compose="# OpenJevX $version with Docker on any VPS, no clone needed: copy this one file, then
#   OPENJEVX_PASSWORD=<12+ letters/digits> docker compose up -d --build
# (the image downloads the 8-bit model while it builds). It listens on 127.0.0.1 only: the decision API has
# no password. Reach it over an SSH tunnel, or open the port to your own network.
# Generated by deploy/render.sh from deploy/VERSION.
services:
  openjevx:
    build:
      context: https://github.com/$repo.git#$image_ref
    ports:
      - \"127.0.0.1:21118:21118\"
    environment:
      OPENJEVX_PASSWORD: \${OPENJEVX_PASSWORD:?set OPENJEVX_PASSWORD (12+ letters/digits)}
    restart: unless-stopped"

if [ "${1:-}" = --check ]; then
  [ "$(cat deploy/cloud-init.yaml)" = "$cloud_init" ] && [ "$(cat deploy/docker-compose.yml)" = "$compose" ] \
    || { echo "render.sh: deploy/cloud-init.yaml or deploy/docker-compose.yml is stale; run deploy/render.sh" >&2; exit 1; }
  echo "render.sh: up to date"
else
  printf '%s\n' "$cloud_init" > deploy/cloud-init.yaml
  printf '%s\n' "$compose" > deploy/docker-compose.yml
  echo "render.sh: wrote deploy/cloud-init.yaml and deploy/docker-compose.yml for $version"
fi
